[features]
seeds = true
skip-lint = false

[programs.localnet]
solana_rfq = "J32rnah2cKSL1nrMw3HQS8A8Lx17JvjY6WNn5qQSyGib"

[programs.devnet]
solana_rfq = "J32rnah2cKSL1nrMw3HQS8A8Lx17JvjY6WNn5qQSyGib"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "NO_DNA=1 anchor test"
